### ISSUE TITLE
[fix]: Can't make it work, better documentation please?

### ISSUE THREAD

**Issue by piuccio** [posthtml/posthtml-cli#261]
Hi, I just tried to use this module but I'm lost

```
npm install posthtml-cli
./node_modules/.bin/posthtml -i index.html -o www/index.html
```

Errors with
```
(node:2646) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'post-load-plugins'
(node:2646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Then I've tried
```
npm install post-load-plugins@0.0.15
./node_modules/.bin/posthtml -i index.html -o www/index.html
```

Errors with
```
(node:2748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'indexOf' of undefined
```

I tried adding a bit more debugging and I get

```
TypeError: Cannot read property 'indexOf' of undefined
    at node_modules/post-config/lib/index.js:1:1498
    at Array.forEach (<anonymous>)
    at node_modules/post-config/lib/index.js:1:1058
    at Array.reduce (<anonymous>)
    at exports.default (node_modules/post-config/lib/index.js:1:785)
    at node_modules/post-load-plugins/lib/index.js:1:1337
    at PostHTML.<anonymous> (node_modules/posthtml/lib/index.js:143:7)
    at node_modules/posthtml/lib/index.js:173:5
    at new Promise (<anonymous>)
    at PostHTML.process (node_modules/posthtml/lib/index.js:172:10)
```

This happens in a minified file. I don't want to spend time figuring out what's wrong.

I tired adding a `configuration.json`, adding config in `package.json`, installing a bunch of plugins but nothing seems to work.

Can you expand the documentation or provide better error messages for people who use this package for the first time?

**Comment by GitScrum** [comment]
@piuccio Hi, Thank you for your feedback. 
This problem has already been announced #252 and #246 , I try to find the time to lose this bug

**Comment by GitScrum** [comment]
@piuccio thanks for your feedback, now everything should work.
